const loginPanel = document.getElementById('loginPanel');
const dashboard = document.getElementById('dashboard');
const loginForm = document.getElementById('loginForm');
const loginError = document.getElementById('loginError');
const toast = document.getElementById('toast');
const tourForm = document.getElementById('tourForm');
const tourCreated = document.getElementById('tourCreated');
const opsTours = document.getElementById('opsTours');
const opsBookings = document.getElementById('opsBookings');
const opsMileage = document.getElementById('opsMileage');

function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(window.t);window.t=setTimeout(()=>toast.classList.remove('show'),2800)}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
async function copyText(text){try{await navigator.clipboard.writeText(text);showToast('Copied to clipboard.')}catch{showToast('Copy failed.')}}

async function checkAuth(){const r=await fetch('/api/operations/me');if(r.ok){loginPanel.classList.add('hidden');dashboard.classList.remove('hidden');loadDashboard()}}
loginForm.addEventListener('submit',async e=>{e.preventDefault();loginError.textContent='';const password=document.getElementById('password').value;const r=await fetch('/api/operations/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok){loginError.textContent=d.error||'Login failed.';return}loginPanel.classList.add('hidden');dashboard.classList.remove('hidden');loadDashboard()})
document.getElementById('logout').onclick=async()=>{await fetch('/api/operations/logout',{method:'POST'});location.reload()};

document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.getElementById(tab.dataset.tab+'Tab').classList.add('active')}));

tourForm.addEventListener('submit',async e=>{e.preventDefault();const button=tourForm.querySelector('button');button.disabled=true;button.textContent='Scheduling…';const body=Object.fromEntries(new FormData(tourForm).entries());try{const r=await fetch('/api/tours',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);tourCreated.classList.remove('hidden');tourCreated.innerHTML=`<div class="copy-row"><strong>Tour scheduled ✓</strong><button class="small-btn" id="copyTourAnnouncement">Copy Discord Announcement</button></div><p class="muted">Paste this directly into your Discord announcement channel.</p><pre>${escapeHtml(d.discordText)}</pre>`;document.getElementById('copyTourAnnouncement').onclick=()=>copyText(d.discordText);tourForm.reset();document.querySelector('[data-tab="tours"]').click();loadDashboard();showToast('Tour created.')}catch(err){showToast(err.message)}finally{button.disabled=false;button.textContent='Schedule Tour'}})

document.getElementById('refresh').onclick=loadDashboard;document.getElementById('refreshBookings').onclick=loadDashboard;document.getElementById('refreshMileage').onclick=loadDashboard;
async function loadDashboard(){const r=await fetch('/api/operations/dashboard');if(!r.ok){location.reload();return}const d=await r.json();renderTours(d.tours||[]);renderBookings(d.bookings||[]);loadMileage()}
function renderTours(tours){
  if(!tours.length){opsTours.innerHTML='<div class="empty">No tours scheduled yet.</div>';return}
  opsTours.innerHTML=`<table class="data-table"><thead><tr><th>Tour</th><th>Date / Time</th><th>Route</th><th>Type</th><th>Capacity</th><th>Status</th><th>Actions</th></tr></thead><tbody>${tours.map(t=>`<tr><td><strong>${escapeHtml(t.title)}</strong><br><span class="muted">${escapeHtml(t.aircraft)}</span></td><td>${escapeHtml(t.date)}<br>${escapeHtml(t.time)}<br><span class="muted">${escapeHtml(t.timezone || 'America/New_York')}</span></td><td>${escapeHtml(t.origin)} → ${escapeHtml(t.destination)}</td><td>${escapeHtml(t.type)}</td><td>${escapeHtml(t.capacity)} seats</td><td><span class="status">${escapeHtml(t.status)}</span></td><td><div class="ops-actions"><button class="small-btn" onclick="copyTourDiscord('${t.id}')">Copy for Discord</button><button class="small-btn" onclick="setTourStatus('${t.id}','Boarding')">Boarding</button><button class="small-btn" onclick="setTourStatus('${t.id}','Completed')">Complete</button><button class="small-btn" onclick="setTourStatus('${t.id}','Cancelled')">Cancel</button><button class="small-btn danger" onclick="deleteTour('${t.id}')">Delete</button></div></td></tr>`).join('')}</tbody></table>`
}

function renderBookings(bookings){
  if(!bookings.length){opsBookings.innerHTML='<div class="empty">No booking requests yet.</div>';return}
  window.currentBookings = bookings;
  opsBookings.innerHTML=`<table class="data-table"><thead><tr><th>Guest</th><th>Tour</th><th>Date / Time</th><th>Route</th><th>Passengers</th><th>Tier / Meals</th><th>Check-In</th><th>Status</th><th>Actions</th></tr></thead><tbody>${bookings.map(b=>`<tr><td><strong>${escapeHtml(b.discord_username)}</strong><br><span class="muted">Roblox: ${escapeHtml(b.roblox_username)}</span><br><span class="muted">Code: ${escapeHtml(b.confirmation_code || '—')}</span></td><td>${escapeHtml(b.tour_type)}</td><td>${escapeHtml(b.date)}<br>${escapeHtml(b.time)}</td><td>${escapeHtml(b.origin)} → ${escapeHtml(b.destination)}${b.notes?`<br><span class="muted">${escapeHtml(b.notes)}</span>`:''}</td><td>${escapeHtml(b.passengers)}</td><td>${escapeHtml(b.membership_tier || 'None')}<br><span class="muted">${escapeHtml(b.meal_service || 'Standard')}</span></td><td>${b.checked_in?'✓ Checked in':'Not checked in'}</td><td><span class="status">${escapeHtml(b.status)}</span>${Number(b.miles_awarded)>0?`<br><span class="muted">+${escapeHtml(b.miles_awarded)} miles</span>`:''}</td><td><div class="ops-actions"><button class="small-btn" onclick="copyBookingDiscord('${b.id}')">Copy for Discord</button><button class="small-btn" onclick="setBookingStatus('${b.id}','Confirmed')">Confirm</button><button class="small-btn" onclick="setBookingStatus('${b.id}','Boarding')">Boarding</button><button class="small-btn" onclick="setBookingStatus('${b.id}','Completed')">Complete</button><button class="small-btn danger" onclick="setBookingStatus('${b.id}','Cancelled')">Cancel</button><button class="small-btn danger" onclick="setBookingStatus('${b.id}','Declined')">Decline</button><button class="small-btn danger" onclick="deleteBooking('${b.id}')">Delete</button></div></td></tr>`).join('')}</tbody></table>`
}

async function loadMileage(){try{const r=await fetch('/api/operations/mileage');if(!r.ok){opsMileage.innerHTML='<div class="empty">Mileage accounts are available after members fly.</div>';return}const d=await r.json();renderMileage(d.accounts||[])}catch{opsMileage.innerHTML='<div class="empty">Could not load mileage accounts.</div>'}}
function renderMileage(accounts){if(!accounts.length){opsMileage.innerHTML='<div class="empty">No mileage accounts yet.</div>';return}opsMileage.innerHTML=`<table class="data-table"><thead><tr><th>Discord</th><th>Roblox</th><th>Miles</th><th>Membership</th><th>Updated</th><th>Member Controls</th></tr></thead><tbody>${accounts.map(a=>`<tr><td><strong>${escapeHtml(a.discord_username)}</strong></td><td>${escapeHtml(a.roblox_username)}</td><td><strong>${Number(a.miles).toLocaleString()}</strong></td><td><span class="status">${escapeHtml(a.tier)}</span></td><td>${a.updated_at?escapeHtml(new Date(a.updated_at).toLocaleString()):'—'}</td><td><div class="ops-actions"><button class="small-btn" onclick="resetMileage('${a.id}')">Reset Miles</button><button class="small-btn danger" onclick="deleteMileageMember('${a.id}')">Delete User + Miles</button></div></td></tr>`).join('')}</tbody></table>`}

window.resetMileage=async id=>{if(!confirm('Reset this member to 0 miles and remove their mileage transaction history?'))return;const r=await fetch('/api/operations/mileage/'+id+'/reset',{method:'PATCH'});const d=await r.json().catch(()=>({}));if(!r.ok){showToast(d.error||'Could not reset miles.');return}loadMileage();showToast('Member miles reset to 0.');};
window.deleteMileageMember=async id=>{if(!confirm('Delete this user permanently? This removes their mileage account, mileage history, and matching booking records. This cannot be undone.'))return;const r=await fetch('/api/operations/members/'+id,{method:'DELETE'});const d=await r.json().catch(()=>({}));if(!r.ok){showToast(d.error||'Could not delete user.');return}loadDashboard();showToast('User and mileage data deleted.');};
window.setTourStatus=async(id,status)=>{if(status==='Cancelled'&&!confirm('Cancel this tour? Existing bookings will remain visible and can be managed separately.'))return;const r=await fetch('/api/tours/'+id+'/status',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const d=await r.json();if(!r.ok){showToast(d.error||'Could not update tour.');return}loadDashboard();showToast(status==='Cancelled'?'Tour cancelled.':'Tour status updated.')};
window.deleteTour=async id=>{if(!confirm('Delete this tour permanently? This cannot be undone.'))return;const r=await fetch('/api/tours/'+id,{method:'DELETE'});const d=await r.json().catch(()=>({}));if(!r.ok){showToast(d.error||'Could not delete tour.');return}loadDashboard();showToast('Tour deleted.')};
window.copyTourDiscord=async id=>{try{const r=await fetch('/api/operations/dashboard');if(!r.ok)throw new Error();const d=await r.json();const tour=(d.tours||[]).find(x=>x.id===id);if(!tour)throw new Error();const timestamp=Number(tour.start_timestamp||0);const timeBlock=timestamp?`📅 **Date:** <t:${timestamp}:D>\n⏰ **Time:** <t:${timestamp}:t>\n🕒 **Starts:** <t:${timestamp}:F> (<t:${timestamp}:R>)`:`📅 **Date:** ${tour.date}\n⏰ **Time:** ${tour.time}`;const text=`@everyone\n\n# ✈️ ${tour.title} #\n\n🌎 **TOUR DETAILS**\n\n${timeBlock}\n🛫 **Route:** ${tour.origin} → ${tour.destination}\n✈️ **Aircraft:** ${tour.aircraft}\n👥 **Capacity:** ${tour.capacity}\n🎟️ **Type:** ${tour.type}\n\n${tour.description?tour.description+'\n\n':''}🔗 **Book / Details:** ${location.origin}/#tours\n\nPTFS Tour Services\nYour Flight. Your Tour. Your Experience.`;await copyText(text)}catch{showToast('Could not generate the Discord announcement.')}};
window.copyBookingDiscord=async id=>{try{const r=await fetch('/api/bookings/'+id+'/discord');const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not generate the message.');await copyText(d.discordText)}catch(err){showToast(err.message||'Could not generate the Discord message.')}};
window.deleteBooking=async id=>{if(!confirm('Delete this booking permanently? This cannot be undone.'))return;const r=await fetch('/api/bookings/'+id,{method:'DELETE'});const d=await r.json().catch(()=>({}));if(!r.ok){showToast(d.error||'Could not delete booking.');return}loadDashboard();showToast('Booking deleted.')};
window.setBookingStatus=async(id,status)=>{if(status==='Cancelled'&&!confirm('Cancel this booking? It will remain in the Operations history with status Cancelled.'))return;const r=await fetch('/api/bookings/'+id+'/status',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const d=await r.json();if(!r.ok){showToast(d.error||'Could not update booking.');return}loadDashboard();if(d.mileageAward?.miles){showToast(`Booking completed. ${d.mileageAward.miles} miles awarded.`)}else{showToast(status==='Cancelled'?'Booking cancelled.':'Booking status updated.')}};
checkAuth();
